name: CRIAR ANSIBLE

on:
  workflow_call:
  
    inputs:
      ec2_public_ip:
        description: "IP público da EC2"
        required: true
        type: string

      private_key_pem: 
        required: true
        type: string

jobs:

  ansible:
    runs-on: ubuntu-latest

    env:
      TF_VAR_account1_access_key: ${{ secrets.ACCOUNT1_ACCESS_KEY }}
      TF_VAR_account1_secret_key: ${{ secrets.ACCOUNT1_SECRET_KEY }}

    steps:

      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Configurar chave SSH 
        run: |
          mkdir -p ~/.ssh
          cat << 'EOF' > ~/.ssh/ec2_key
          ${{ inputs.private_key_pem }}
          EOF
          chmod 600 ~/.ssh/ec2_key

          chmod 600 ~/.ssh/ec2_key

      - name: Esperar SSH da EC2
        run: |

          IP="${{ inputs.ec2_public_ip }}"

          echo "Esperando SSH em $IP"

          for i in {1..30}
          do
            if ssh \
              -o BatchMode=yes \
              -o ConnectTimeout=5 \
              -o ConnectionAttempts=1 \
              -o StrictHostKeyChecking=no \
              -i ~/.ssh/ec2_key \
              "ubuntu@$IP" \
              "echo conectado"; then

              echo "EC2 acessível via SSH."
              exit 0
            fi

            echo "SSH ainda indisponível (tentativa $i/30)."

            sleep 10
          done

          echo "A instância não ficou acessível por SSH em 5 minutos." >&2
          exit 1

      - name: Executar Ansible
        run: |

          IP="${{ inputs.ec2_public_ip }}"

          ansible-playbook \
            -i "${IP}," \\
            -u ubuntu \
            --private-key ~/.ssh/ec2_key \
            ansible/playbook.yml

