name: Create Infrastructure

on:
  workflow_dispatch:

jobs:

  terraform:
    name: Criar infraestrutura
    uses: ./.github/workflows/terraform.yml
    secrets: inherit

  ansible:
    name: Configurar EC2
    needs: terraform
    uses: ./.github/workflows/ansible.yml

    with:
      ec2_public_ip: ${{ needs.terraform.outputs.ec2_public_ip }}
      private_key_pem: ${{ needs.terraform.outputs.private_key_pem }}

    secrets: inherit


  # docker-compose:
  #   name: Copiar Docker Compose
  #   needs: ansible
  #   uses: ./.github/workflows/reusable/docker.yml

  #   with:
  #     ec2_public_ip: ${{ needs.terraform.outputs.ec2_public_ip }}

  #   secrets: inherit
