name: Build and Push Multiple Images

on:
  workflow_dispatch:
      
jobs:

  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:

      # ==========================================
      # Checkout dos repositórios
      # ==========================================

      - name: Checkout repository Java
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Pesquisa-e-Inovacao-Grupo-8/BACK-END-JAVA.git
          token: ${{ secrets.REPO_TOKEN }}
          path: java

      - name: Checkout repository Infinity Pay
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Pesquisa-e-Inovacao-Grupo-8/API-INFINITY-PAY.git
          token: ${{ secrets.REPO_TOKEN }}
          path: infinity-pay

      - name: Checkout repository API Whatsapp
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Pesquisa-e-Inovacao-Grupo-8/API-WHATSAPP.git
          token: ${{ secrets.REPO_TOKEN }}
          path: whatsapp
      - name: Checkout repository Frontend
        uses: actions/checkout@v4
        with:
          repository: https://github.com/Pesquisa-e-Inovacao-Grupo-8/FRONT-END-REACT.git
          token: ${{ secrets.REPO_TOKEN }}
          path: frontend


      # ==========================================
      # Login Docker Hub
      # ==========================================

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}


      # ==========================================
      # Configurar Docker Buildx
      # ==========================================

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3


      # ==========================================
      # Build + Push Java
      # ==========================================

      - name: Build and Push Java
        uses: docker/build-push-action@v6
        with:
          context: ./java
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/java:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/java:${{ github.sha }}


      # ==========================================
      # Build + Push Python
      # ==========================================

      - name: Build and Push Infinity Pay
        uses: docker/build-push-action@v6
        with:
          context: ./infinity-pay
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/infinity-pay:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/infinity-pay:${{ github.sha }}

      - name: Build and Push Whatsapp
        uses: docker/build-push-action@v6
        with:
          context: ./whatsapp
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/whatsapp:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/whatsapp:${{ github.sha }}


      # ==========================================
      # Build + Push Frontend
      # ==========================================

      - name: Build and Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frontend:${{ github.sha }}
