name: CRIAR TERRAFORM

on:
  workflow_call:

    outputs:
      ec2_public_ip:
        description: "IP público da EC2 criada pelo Terraform"
        value: ${{ jobs.terraform.outputs.ec2_public_ip }} 

      private_key_pem:
        description: "Chave privada PEM para acessar a EC2"
        value: ${{ jobs.terraform.outputs.private_key_pem }}

jobs:

  terraform:
    runs-on: ubuntu-latest

    outputs:
      ec2_public_ip: ${{ steps.ec2_ip.outputs.ec2_public_ip }}
      private_key_pem: ${{ steps.private_key.outputs.private_key_pem }}

    env:
      TF_VAR_account1_access_key: ${{ secrets.ACCOUNT1_ACCESS_KEY }}
      TF_VAR_account1_secret_key: ${{ secrets.ACCOUNT1_SECRET_KEY }}

    steps:

      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Configurando credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ACCOUNT1_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ACCOUNT1_SECRET_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Iniciando Terraform
        working-directory: ./terraform
        run: terraform init

      - name: Listar arquivos
        working-directory: ./terraform
        run: |
          pwd
          ls -la

      - name: Gerando plano
        working-directory: ./terraform
        run: terraform plan

      - name: Aplicando mudanças
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Obtendo IP público da EC2
        id: ec2_ip
        working-directory: ./terraform
        run: |
          IP=$(terraform output -raw ec2_public_ip)

          echo "EC2 Public IP: $IP"
          echo "ec2_public_ip=$IP" >> "$GITHUB_OUTPUT"

      - name: Obtendo Chave Privada da EC2
        id: private_key
        working-directory: ./terraform
        run: |
          PRIVATE_KEY=$(terraform output -raw private_key_pem)

          echo "private_key_pem<<EOF" >> $GITHUB_OUTPUT
          echo "$PRIVATE_KEY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT