name: Build

on:
  push:
    branches: ["release"]

jobs:
  sonar:
    uses: ./Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/tree/main/.github/workflows/sonarqube/node
      sonar_project_key: "${{github.repository}}"
      sonar_organization: "${{github.organization}}"
    secrets: inherit
