name: Create Ansible

on:
  workflow_call:
    secrets:
      EC2_DNS:
        description: "IP público da EC2"
        required: true

jobs:
  ansible:
    runs-on: vm-ec2-runner-aws

    steps:

      - name: Checkout repositório
        uses: actions/checkout@v4

      - name: Instalar Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Executar Ansible
        run: |
          IP="${{ secrets.EC2_DNS }}"

          ansible-playbook \
            -i "${IP}," \
            -u ubuntu \
            --private-key /home/ubuntu/.ssh/vm-key-pair.pem \
            ansible/playbook.yml