name: Build

on:
  workflow_call:

jobs:
  sonar:
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/sonarqube/node.yml@main
    with:
      sonar_project_key: ${{ github.repository }}
      sonar_organization: ${{ github.repository_owner }}
    secrets: inherit

