name: BUILD PYTHON - DOCKER

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string
      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string

jobs:
  # ---------- DEV ----------
  dev-sonarqube:
    name: DEV - SonarCloud Analysis
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/sonarqube-python.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  dev-docker-build:
    name: DEV - Docker Build
    needs: dev-sonarqube
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/docker-build.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  dev-deploy:
    name: DEV - Deploy to EC2
    needs: dev-docker-build
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/deploy-on-ec2.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  # ---------- PRD ----------
  prd-sonarqube:
    name: PRD - SonarCloud Analysis
    needs: dev-deploy
    environment: PRD
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/sonarqube-python.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  prd-docker-build:
    name: PRD - Docker Build
    needs: prd-sonarqube
    environment: PRD
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/docker-build.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  prd-deploy:
    name: PRD - Deploy to EC2
    needs: prd-docker-build
    environment: PRD
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/deploy-on-ec2.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit