name: BUILD JAVA - DOCKER

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string
      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string
        
jobs:

  sonarqube:
    name: SonarCloud Analysis
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/sonarqube.yml@main
    with:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
      
  # build-image:
  #   name: Build Docker Images
  #   uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/docker.yml@main
  #   with:
  #     GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
  #     GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}

  deploy:
    name: Deploy to EC2 - PUBLIC
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/deploy-public.yml@main


