name: BUILD JAVA - DOCKER

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string

jobs:
  sonarqube:
    name: SonarCloud Analysis
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/sonarqube-java.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  docker-qa:
    name: Docker Build - QA
    if: github.ref != 'refs/heads/master'
    needs: sonarqube
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/docker-build-qa.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  deploy-qa:
    name: Deploy to EC2 - QA
    if: github.ref != 'refs/heads/master'
    needs: docker-qa
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/deploy-on-ec2-qa.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets:
      EC2_DNS_QA: ${{ secrets.EC2_PRIVATE_DNS_QA }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  docker-prd:
    name: Docker Build - PRD
    needs: sonarqube
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/docker-build-prd.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets: inherit

  deploy-prd:
    name: Deploy to EC2 - PRD
    if: github.ref == 'refs/heads/master' 
    needs: docker-prd
    uses: Pesquisa-e-Inovacao-Grupo-8/TEMPLATES-PIPELINES/.github/workflows/deploy-on-ec2-prd.yml@main
    with:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
    secrets:
      EC2_DNS_PRD: ${{ secrets.EC2_PRIVATE_DNS_PRD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}