name: DEPLOY ON EC2 - QA E PRD

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string

    secrets:
      EC2_DNS_PRD:
        description: "EC2 DNS PRD"
        required: true

      DOCKERHUB_USERNAME:
        description: "Docker Hub Username"
        required: true
      

jobs:
  deploy-ec2-prd:
    name: Deploy to EC2 - PRD
    runs-on: vm-ec2-aws-prd
    environment: PRD

    steps:
      - name: Deploy Application
        shell: bash
        run: |
          ssh \
            -i "/home/ubuntu/.ssh/vm-key-pair.pem" \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_DNS_PRD }} << 'EOF'

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"

          if [ -d "$PROJECT_DIR" ]; then
            echo "Diretório já existe: $PROJECT_DIR"
          else
            echo "Diretório não existe. Criando..."
            mkdir -p "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          USERNAME=$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '\r\n')
          REPOSITORY=$(echo -n "${{ inputs.GITHUB_REPOSITORY_NAME }}" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')
          IMAGE="$USERNAME/$REPOSITORY-prd:${{ github.run_number }}"

          docker pull "$IMAGE"

          sed -i "s|image:.*|image: $IMAGE|g" docker-compose.yml

          sudo docker compose down
          sudo docker compose up -d

          EOF


  rollback-ec2-prd:
    name: Rollback EC2 - PRD
    needs: deploy-ec2-prd
    runs-on: vm-ec2-aws-prd
    environment: ROLLBACK
    steps:

      - name: Rollback Application
        shell: bash

        run: |

          echo "Iniciando rollback..."


          USERNAME=$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '\r\n')
          REPOSITORY=$(echo -n "${{ inputs.GITHUB_REPOSITORY_NAME }}" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')
          PREVIOUS_RUN=$(( ${{ github.run_number }} - 1 ))
          PREVIOUS_IMAGE="$USERNAME/$REPOSITORY-prd:$PREVIOUS_RUN"
          echo "Imagem anterior: $PREVIOUS_IMAGE"

          ssh \
            -i "/home/ubuntu/.ssh/vm-key-pair.pem" \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_DNS_PRD }} << 'EOF'

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"

          cd "$PROJECT_DIR"

          if [ -f docker-compose.yml ]; then
            echo "docker-compose.yml exists."
          else
            curl -fsSL \
              -H "Authorization: Bearer $DEPLOY_TOKEN" \
              -H "Accept: application/vnd.github.raw+json" \
              "https://api.github.com/repos/Pesquisa-e-Inovacao-Grupo-8/${{ inputs.GITHUB_REPOSITORY_NAME }}/contents/docker-compose.yml" \
              -o docker-compose.yml
          fi


          USERNAME=$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '\r\n')
          REPOSITORY=$(echo -n "${{ inputs.GITHUB_REPOSITORY_NAME }}" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')
          PREVIOUS_RUN=$(( ${{ github.run_number }} - 1 ))
          PREVIOUS_IMAGE="$USERNAME/$REPOSITORY-prd:$PREVIOUS_RUN"
          echo "Restaurando: $PREVIOUS_IMAGE"

          docker pull "$PREVIOUS_IMAGE"

          sed -i "s|image:.*|image: $PREVIOUS_IMAGE|g" docker-compose.yml
          sudo docker compose down
          sudo docker compose up -d

          echo "Rollback PRD concluído."

          EOF

