name: Deploy to EC2 - PRIVATE

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string
    secrets:
      EC2_PRIVATE_DNS:
        description: "EC2 Private DNS"
        required: true

jobs:

  teste-conexao:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Test Connection
        shell: bash
        run: |
          ssh -i "/home/ubuntu/.ssh/vm-ec2-default-key.pem" ubuntu@${{ secrets.EC2_PRIVATE_DNS }} << 'EOF'

          hostname
          echo "Deploying ${{ inputs.GITHUB_REPOSITORY_NAME }} to EC2 Private Instance"
          echo "GitHub Organization: ${{ inputs.GITHUB_ORGANIZATION }}"
          echo "GitHub Repository: ${{ inputs.GITHUB_REPOSITORY_NAME }}"
          echo "GitHub Run Number: ${{ github.run_number }}"
          echo "GitHub Run ID: ${{ github.run_id }}"
          echo "TESTE BEM SUCEDIDO"

          EOF


  confirm-project-directory:
    needs: teste-conexao
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Confirm Project Directory
        shell: bash
        run: |
          ssh -i "/home/ubuntu/.ssh/vm-ec2-default-key.pem" ubuntu@${{ secrets.EC2_PRIVATE_DNS }} << 'EOF'

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"

          if [ -d "$PROJECT_DIR" ]; then
            echo "Diretório já existe: $PROJECT_DIR"
          else
            echo "Diretório não existe. Criando..."
            mkdir -p "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          echo "Diretório atual:"
          pwd

          echo "Conteúdo:"
          ls -la

          EOF


  deploy-application:
    needs: confirm-project-directory
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Deploy Application
        shell: bash
        run: |
          ssh -i "/home/ubuntu/.ssh/vm-ec2-default-key.pem" ubuntu@${{ secrets.EC2_PRIVATE_DNS }} << 'EOF'

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"

          cd "$PROJECT_DIR"

          echo "Diretório atual:"
          pwd

          echo "Iniciando deploy..."

          EOF
