name: Deploy to EC2

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string
    secrets:
      EC2_DNS:
        description: "EC2 DNS"
        required: true
      DOCKERHUB_USERNAME:
        description: "Docker Hub Username"
        required: true
      
jobs:
  deploy-ec2-dev:
    name: Deploy to EC2 - DEV
    runs-on: vm-ec2-runner-aws
    
    steps:
      - name: Deploy Application
        shell: bash
        run: |
          ssh \
            -i "/home/ubuntu/.ssh/vm-key-pair.pem" \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_DNS }} << 'EOF'

          sudo apt update
          sudo apt install -y docker.io docker-compose

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"

          if [ -d "$PROJECT_DIR" ]; then
            echo "Diretório já existe: $PROJECT_DIR"
          else
            echo "Diretório não existe. Criando..."
            mkdir -p "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          USERNAME=$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '\r\n')
          REPOSITORY=$(echo -n "${{ inputs.GITHUB_REPOSITORY_NAME }}" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')
          IMAGE="$USERNAME/$REPOSITORY:${{ github.run_number }}"

          docker pull "$IMAGE"

          sed -i "s|image:.*|image: $IMAGE|g" docker-compose.yml

          sudo docker compose down
          sudo docker compose up -d

          EOF

  deploy-ec2-prd:
    name: Deploy to EC2 - PRD
    needs: deploy-ec2-dev
    runs-on: vm-ec2-runner-aws
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: PRD

    steps:
      - name: Deploy Application
        shell: bash
        run: |
          ssh \
            -i "/home/ubuntu/.ssh/vm-key-pair.pem" \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_DNS_PRD }} << 'EOF'

          sudo apt update
          sudo apt install -y docker.io docker-compose

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"

          if [ -d "$PROJECT_DIR" ]; then
            echo "Diretório já existe: $PROJECT_DIR"
          else
            echo "Diretório não existe. Criando..."
            mkdir -p "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          USERNAME=$(echo -n "${{ secrets.DOCKERHUB_USERNAME }}" | tr -d '\r\n')
          REPOSITORY=$(echo -n "${{ inputs.GITHUB_REPOSITORY_NAME }}" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')
          IMAGE="$USERNAME/$REPOSITORY:${{ github.run_number }}"

          docker pull "$IMAGE"

          sed -i "s|image:.*|image: $IMAGE|g" docker-compose.yml

          sudo docker compose down
          sudo docker compose up -d

          EOF