name: Deploy to EC2 - PUBLIC

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string

jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, self-hosted-public-ec2]

    steps:
      - name: ECHO TESTE - EC2 RUNNER
        run: |
          echo "GITHUB_REPOSITORY: ${{ inputs.GITHUB_REPOSITORY_NAME }}"
          echo "GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}"