name: Deploy to EC2 - PRIVATE

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string
    secrets:
      EC2_DNS:
        description: "EC2 Private DNS"
        required: true

jobs:
  deploy-ec2-private:
    runs-on: [self-hosted, Linux, X64]
    steps:
      - name: Test Connection
        shell: bash
        run: |
          ssh -i "/home/ubuntu/.ssh/vm-ec2-default-key.pem" ubuntu@${{ secrets.EC2_DNS }} << 'EOF'

          hostname
          echo "Deploying ${{ inputs.GITHUB_REPOSITORY_NAME }} to EC2 Private Instance"
          echo "GitHub Organization: ${{ inputs.GITHUB_ORGANIZATION }}"
          echo "GitHub Repository: ${{ inputs.GITHUB_REPOSITORY_NAME }}"
          echo "GitHub Run Number: ${{ github.run_number }}"
          echo "GitHub Run ID: ${{ github.run_id }}"
          echo "TESTE BEM SUCEDIDO"

          EOF

      - name: Deploy Application
        shell: bash
        run: |
          ssh -i "/home/ubuntu/.ssh/vm-ec2-default-key.pem" ubuntu@${{ secrets.EC2_DNS }} << 'EOF'

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"


          if [ -d "$PROJECT_DIR" ]; then
            echo "Diretório já existe: $PROJECT_DIR"
          else
            echo "Diretório não existe. Criando..."
            mkdir -p "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          echo "Iniciando deploy..."

          # Pull the latest Docker image from Docker Hub
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.GITHUB_REPOSITORY_NAME }}:${{ github.run_number }}
          sed docker-compose.yml -i "s|image:.*|image: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.GITHUB_REPOSITORY_NAME }}:${{ github.run_number }}|g"
          docker-compose down
          docker-compose up -d

          EOF
