name: Deploy to EC2 - PRIVATE

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string
    secrets:
      EC2_DNS:
        description: "EC2 DNS"
        required: true

jobs:
  deploy-ec2-private:
    runs-on: vm-ec2-runner-aws
    steps:
      - name: Test Connection
        shell: bash
        run: |
          ssh -i "/home/ubuntu/.ssh/vm-key-pair.pem" ubuntu@${{ secrets.EC2_DNS }} << 'EOF'

          hostname
          echo "Deploying ${{ inputs.GITHUB_REPOSITORY_NAME }} to EC2 Private Instance"
          echo "GitHub Organization: ${{ inputs.GITHUB_ORGANIZATION }}"
          echo "GitHub Repository: ${{ inputs.GITHUB_REPOSITORY_NAME }}"
          echo "GitHub Run Number: ${{ github.run_number }}"
          echo "GitHub Run ID: ${{ github.run_id }}"
          echo "TESTE BEM SUCEDIDO"

          EOF

      - name: Deploy Application
        shell: bash
        run: |
          ssh \
            -i "/home/ubuntu/.ssh/vm-key-pair.pem" \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_DNS }} << 'EOF'

          sudo apt update
          sudo apt install -y docker.io docker-compose

          PROJECT_DIR="/home/ubuntu/${{ inputs.GITHUB_REPOSITORY_NAME }}"


          if [ -d "$PROJECT_DIR" ]; then
            echo "Diretório já existe: $PROJECT_DIR"
          else
            echo "Diretório não existe. Criando..."
            mkdir -p "$PROJECT_DIR"
          fi

          cd "$PROJECT_DIR"

          echo "Iniciando deploy..."

          USERNAME=$(echo -n "$DOCKERHUB_USERNAME" | tr -d '\r\n')
          REPOSITORY=$(echo -n "$GITHUB_REPOSITORY_NAME" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')

          IMAGE="$USERNAME/$REPOSITORY:${{ github.run_number }}"

          docker pull "$IMAGE"

          EOF
