name: Deploy to EC2 - PUBLIC

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Test Runner
        run: |
          echo "Runner funcionando!"
          hostname
