name: Build and Push - Docker Hub

on:
  workflow_call:
    inputs:
      GITHUB_REPOSITORY_NAME:
        description: "GitHub Repository Name"
        required: true
        type: string

      GITHUB_ORGANIZATION:
        description: "GitHub Organization Name"
        required: true
        type: string

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  docker:
    name: Build Docker Images
    runs-on: ubuntu-latest

    env:
      GITHUB_REPOSITORY_NAME: ${{ inputs.GITHUB_REPOSITORY_NAME }}
      GITHUB_ORGANIZATION: ${{ inputs.GITHUB_ORGANIZATION }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          USERNAME=$(echo -n "$DOCKERHUB_USERNAME" | tr -d '\r\n')
          REPOSITORY=$(echo -n "$GITHUB_REPOSITORY_NAME" | tr -d '\r\n' | tr '[:upper:]' '[:lower:]')

          IMAGE="$USERNAME/$REPOSITORY:${{ github.run_number }}"

          echo "Repository: $REPOSITORY"
          echo "Organization: $GITHUB_ORGANIZATION"
          echo "Image: $IMAGE"

          docker build -t "$IMAGE" .
          docker push "$IMAGE"
