name: RUNNER TESTE

on:
  workflow_dispatch:

jobs:
  runner-test:
    name: Runner Sanity Check
    on: workflow_dispatch
    jobs:
      test:
        runs-on: self-hosted
        steps:
          - run: echo "ok"; hostname

