name: BACK-END-JAVA

on:
  workflow_dispatch:

jobs:
  teste-conexao:
    runs-on: [self-hosted, Linux, X64]

    steps:
      - name: Test Runner
        run: |
          ssh -i "vm-ec2-default-key.pem" ubuntu@ec2${{ secrets.EC2_PUBLIC_IP }}.compute-1.amazonaws.com
          mkdir TESTE