name: TESTE - RUNNER SSH

on:
  workflow_dispatch:

jobs:
  teste-conexao:
    runs-on: vm-ec2-runner-aws

    steps:
      - name: Test Runner
        shell: bash
        run: |
          ssh \
            -i "/home/ubuntu/.ssh/vm-key-pair.pem" \
            -o StrictHostKeyChecking=no \
            ubuntu@${{ secrets.EC2_PRIVATE_DNS }} << 'EOF'

          echo "Conectado na EC2"
          pwd
          ls -la
          mkdir -p teste
          ls -la

          EOF
