name: TESTE - RUNNER SSH

on:
  workflow_dispatch:

jobs:
  teste-conexao:
    runs-on: vm-ec2-runner-aws

    steps:
      - name: Test Runner
        shell: bash
        run: |
           ssh -i "/home/ubuntu/.ssh/vm-key-pair.pem" ubuntu@${{ secrets.EC2_PRIVATE_DNS }} << 'EOF'
           "
           pwd
           ls -la
           mkdir teste
           "
           EOF

